[2024-04-30T00:06:17.116+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T00:06:17.209+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yellow_cab.file_exception manual__2024-04-30T00:02:41.393402+00:00 [queued]>
[2024-04-30T00:06:17.225+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yellow_cab.file_exception manual__2024-04-30T00:02:41.393402+00:00 [queued]>
[2024-04-30T00:06:17.226+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T00:06:17.278+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): file_exception> on 2024-04-30 00:02:41.393402+00:00
[2024-04-30T00:06:17.337+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=155) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-30T00:06:17.353+0000] {standard_task_runner.py:63} INFO - Started process 166 to run task
[2024-04-30T00:06:17.347+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_yellow_cab', 'file_exception', 'manual__2024-04-30T00:02:41.393402+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_cab.py', '--cfg-path', '/tmp/tmpp4zeeru7']
[2024-04-30T00:06:17.378+0000] {standard_task_runner.py:91} INFO - Job 154: Subtask file_exception
[2024-04-30T00:06:17.791+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_yellow_cab.file_exception manual__2024-04-30T00:02:41.393402+00:00 [running]> on host fa551f826898
[2024-04-30T00:06:18.021+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_yellow_cab' AIRFLOW_CTX_TASK_ID='file_exception' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T00:02:41.393402+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T00:02:41.393402+00:00'
[2024-04-30T00:06:18.024+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T00:06:18.055+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-30T00:06:18.056+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T00:06:18.075+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_yellow_cab, task_id=file_exception, execution_date=20240430T000241, start_date=20240430T000617, end_date=20240430T000618
[2024-04-30T00:06:18.131+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-30T00:06:18.149+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T00:06:18.151+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
