[2024-04-28T18:06:53.320+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T18:06:53.364+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yellow_cab.download_file manual__2024-04-28T18:06:51.080717+00:00 [queued]>
[2024-04-28T18:06:53.374+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yellow_cab.download_file manual__2024-04-28T18:06:51.080717+00:00 [queued]>
[2024-04-28T18:06:53.374+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T18:06:53.398+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): download_file> on 2024-04-28 18:06:51.080717+00:00
[2024-04-28T18:06:53.405+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=78) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-28T18:06:53.414+0000] {standard_task_runner.py:63} INFO - Started process 79 to run task
[2024-04-28T18:06:53.412+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_yellow_cab', 'download_file', 'manual__2024-04-28T18:06:51.080717+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_cab.py', '--cfg-path', '/tmp/tmpmskcqikk']
[2024-04-28T18:06:53.417+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask download_file
[2024-04-28T18:06:53.550+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_yellow_cab.download_file manual__2024-04-28T18:06:51.080717+00:00 [running]> on host 6a7b1bc8d40a
[2024-04-28T18:06:53.714+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_yellow_cab' AIRFLOW_CTX_TASK_ID='download_file' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T18:06:51.080717+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T18:06:51.080717+00:00'
[2024-04-28T18:06:53.715+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T18:06:53.758+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T18:06:53.759+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/scripts.py", line 9, in file_download
    blob_service_client = BlobServiceClient.from_connection_string("AZURE_STORAGE_CONNECTION_STRING")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/azure/storage/blob/_blob_service_client.py", line 190, in from_connection_string
    account_url, secondary, credential = parse_connection_str(conn_str, credential, 'blob')
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/azure/storage/blob/_shared/base_client.py", line 371, in parse_connection_str
    raise ValueError("Connection string is either blank or malformed.")
ValueError: Connection string is either blank or malformed.
[2024-04-28T18:06:53.777+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dag_yellow_cab, task_id=download_file, execution_date=20240428T180651, start_date=20240428T180653, end_date=20240428T180653
[2024-04-28T18:06:53.799+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task download_file (Connection string is either blank or malformed.; 79)
[2024-04-28T18:06:53.843+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-28T18:06:53.867+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T18:06:53.870+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
