[2024-05-01T00:11:54.121+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T00:11:54.200+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yellow_cab.calculate_mean_time scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T00:11:54.214+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yellow_cab.calculate_mean_time scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T00:11:54.215+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T00:11:54.242+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): calculate_mean_time> on 2024-04-30 00:00:00+00:00
[2024-05-01T00:11:54.286+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=393) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-01T00:11:54.297+0000] {standard_task_runner.py:63} INFO - Started process 402 to run task
[2024-05-01T00:11:54.301+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_yellow_cab', 'calculate_mean_time', 'scheduled__2024-04-30T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp1yj21l83']
[2024-05-01T00:11:54.312+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask calculate_mean_time
[2024-05-01T00:11:54.613+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_yellow_cab.calculate_mean_time scheduled__2024-04-30T00:00:00+00:00 [running]> on host ee85e0733ed4
[2024-05-01T00:11:55.014+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_yellow_cab' AIRFLOW_CTX_TASK_ID='calculate_mean_time' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-30T00:00:00+00:00'
[2024-05-01T00:11:55.017+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T00:15:09.202+0000] {local_task_job_runner.py:240} INFO - Task exited with return code -9
[2024-05-01T00:15:10.150+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T00:15:10.154+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-01T23:28:41.350+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T23:28:41.370+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yellow_cab.calculate_mean_time scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T23:28:41.378+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yellow_cab.calculate_mean_time scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T23:28:41.378+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T23:28:41.390+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): calculate_mean_time> on 2024-04-30 00:00:00+00:00
[2024-05-01T23:28:41.395+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-01T23:28:41.396+0000] {standard_task_runner.py:63} INFO - Started process 85 to run task
[2024-05-01T23:28:41.397+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_yellow_cab', 'calculate_mean_time', 'scheduled__2024-04-30T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpim1zzs3w']
[2024-05-01T23:28:41.399+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask calculate_mean_time
[2024-05-01T23:28:41.445+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_yellow_cab.calculate_mean_time scheduled__2024-04-30T00:00:00+00:00 [running]> on host cfaf22ab3131
[2024-05-01T23:28:41.530+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_yellow_cab' AIRFLOW_CTX_TASK_ID='calculate_mean_time' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-30T00:00:00+00:00'
[2024-05-01T23:28:41.531+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T23:28:41.545+0000] {scripts.py:73} INFO - Start average calculation
[2024-05-01T23:28:41.568+0000] {scripts.py:76} INFO - calculation completed
[2024-05-01T23:28:41.569+0000] {scripts.py:85} INFO - generating file
[2024-05-01T23:28:41.569+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T23:28:41.570+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/scripts.py", line 80, in calculation_file
    response_filepath, filename = generate_file(average_duration, first_timestamp, last_timestamp)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/scripts.py", line 86, in generate_file
    filename = str(first_timestamp.year) + '-' + str(first_timestamp.month) + '.txt'
                   ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'year'
[2024-05-01T23:28:41.581+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dag_yellow_cab, task_id=calculate_mean_time, execution_date=20240430T000000, start_date=20240501T232841, end_date=20240501T232841
[2024-05-01T23:28:41.595+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task calculate_mean_time ('NoneType' object has no attribute 'year'; 85)
[2024-05-01T23:28:41.619+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T23:28:41.635+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T23:28:41.637+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
