[2024-04-29T17:57:01.511+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T17:57:01.531+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yellow_cab.copy_into_table manual__2024-04-29T17:55:51.277362+00:00 [queued]>
[2024-04-29T17:57:01.538+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yellow_cab.copy_into_table manual__2024-04-29T17:55:51.277362+00:00 [queued]>
[2024-04-29T17:57:01.539+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T17:57:01.550+0000] {taskinstance.py:2327} INFO - Executing <Task(CopyFromExternalStageToSnowflakeOperator): copy_into_table> on 2024-04-29 17:55:51.277362+00:00
[2024-04-29T17:57:01.558+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=170) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T17:57:01.560+0000] {standard_task_runner.py:63} INFO - Started process 172 to run task
[2024-04-29T17:57:01.566+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_yellow_cab', 'copy_into_table', 'manual__2024-04-29T17:55:51.277362+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_cab.py', '--cfg-path', '/tmp/tmpiu82knu2']
[2024-04-29T17:57:01.569+0000] {standard_task_runner.py:91} INFO - Job 96: Subtask copy_into_table
[2024-04-29T17:57:01.612+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_yellow_cab.copy_into_table manual__2024-04-29T17:55:51.277362+00:00 [running]> on host 93e07c9aa143
[2024-04-29T17:57:01.704+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_yellow_cab' AIRFLOW_CTX_TASK_ID='copy_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T17:55:51.277362+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T17:55:51.277362+00:00'
[2024-04-29T17:57:01.706+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T17:57:01.720+0000] {copy_into_snowflake.py:143} INFO - Executing COPY command...
[2024-04-29T17:57:01.731+0000] {base.py:84} INFO - Using connection ID 'yellowcab_proyect' for task execution.
[2024-04-29T17:57:01.732+0000] {connection.py:386} INFO - Snowflake Connector for Python Version: 3.7.1, Python Version: 3.12.2, Platform: Linux-6.6.22-linuxkit-x86_64-with-glibc2.36
[2024-04-29T17:57:01.733+0000] {connection.py:1211} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-04-29T17:57:02.491+0000] {cursor.py:1032} INFO - query: [ALTER SESSION SET autocommit=True]
[2024-04-29T17:57:02.566+0000] {cursor.py:1045} INFO - query execution done
[2024-04-29T17:57:02.568+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-04-29T17:57:02.592+0000] {sql.py:457} INFO - Running statement: COPY INTO PUBLIC.YELLOWCAB_DATA
             FROM  @%YELLOWCAB_DATA/
        
        
        FILE_FORMAT=(type = 'parquet',field_delimiter = ',', skip_header=1 FIELD_OPTIONALLY_ENCLOSED_BY = '"'), parameters: None
[2024-04-29T17:57:02.593+0000] {cursor.py:1032} INFO - query: [COPY INTO PUBLIC.YELLOWCAB_DATA FROM  @%YELLOWCAB_DATA/   FILE_FORMAT=(type = 'p...]
[2024-04-29T17:57:02.686+0000] {cursor.py:1045} INFO - query execution done
[2024-04-29T17:57:02.700+0000] {connection.py:734} INFO - closed
[2024-04-29T17:57:02.741+0000] {connection.py:740} INFO - No async queries seem to be running, deleting session
[2024-04-29T17:57:02.797+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T17:57:02.798+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/transfers/copy_into_snowflake.py", line 144, in execute
    self._result = self.hook.run(  # type: ignore # mypy does not work well with return_dictionaries=True
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 390, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1136, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002135 (42601): 01b3ff75-0000-5448-0000-0000d81d6029: SQL compilation error:
Option FIELD_DELIMITER is not valid for file format type parquet.
[2024-04-29T17:57:02.807+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dag_yellow_cab, task_id=copy_into_table, execution_date=20240429T175551, start_date=20240429T175701, end_date=20240429T175702
[2024-04-29T17:57:02.820+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 96 for task copy_into_table (002135 (42601): 01b3ff75-0000-5448-0000-0000d81d6029: SQL compilation error:
Option FIELD_DELIMITER is not valid for file format type parquet.; 172)
[2024-04-29T17:57:02.849+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T17:57:02.864+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T17:57:02.866+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
