[2024-04-28T17:41:17.591+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T17:41:17.618+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yellow_cab.validate_file manual__2024-04-28T17:41:14.537797+00:00 [queued]>
[2024-04-28T17:41:17.626+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yellow_cab.validate_file manual__2024-04-28T17:41:14.537797+00:00 [queued]>
[2024-04-28T17:41:17.627+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T17:41:17.639+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): validate_file> on 2024-04-28 17:41:14.537797+00:00
[2024-04-28T17:41:17.643+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-28T17:41:17.645+0000] {standard_task_runner.py:63} INFO - Started process 73 to run task
[2024-04-28T17:41:17.645+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_yellow_cab', 'validate_file', 'manual__2024-04-28T17:41:14.537797+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_cab.py', '--cfg-path', '/tmp/tmpjn9m404p']
[2024-04-28T17:41:17.647+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask validate_file
[2024-04-28T17:41:17.691+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_yellow_cab.validate_file manual__2024-04-28T17:41:14.537797+00:00 [running]> on host a0b954ea3cc8
[2024-04-28T17:41:17.779+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_yellow_cab' AIRFLOW_CTX_TASK_ID='validate_file' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T17:41:14.537797+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T17:41:14.537797+00:00'
[2024-04-28T17:41:17.780+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T17:41:17.793+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-28T17:41:17.794+0000] {logging_mixin.py:188} INFO - file_validation
[2024-04-28T17:41:17.795+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-28T17:41:17.795+0000] {branch.py:36} INFO - Branch into None
[2024-04-28T17:41:17.796+0000] {skipmixin.py:178} INFO - Following branch None
[2024-04-28T17:41:17.805+0000] {skipmixin.py:246} INFO - Skipping tasks [('file_exception', -1)]
[2024-04-28T17:41:17.825+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T17:41:17.835+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_yellow_cab, task_id=validate_file, execution_date=20240428T174114, start_date=20240428T174117, end_date=20240428T174117
[2024-04-28T17:41:17.867+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-28T17:41:17.886+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T17:41:17.888+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
