[2024-04-29T02:14:18.447+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T02:14:18.471+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yellow_cab.file_exception manual__2024-04-29T02:13:36.403066+00:00 [queued]>
[2024-04-29T02:14:18.481+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yellow_cab.file_exception manual__2024-04-29T02:13:36.403066+00:00 [queued]>
[2024-04-29T02:14:18.481+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T02:14:18.494+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): file_exception> on 2024-04-29 02:13:36.403066+00:00
[2024-04-29T02:14:18.500+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=260) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T02:14:18.501+0000] {standard_task_runner.py:63} INFO - Started process 262 to run task
[2024-04-29T02:14:18.502+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_yellow_cab', 'file_exception', 'manual__2024-04-29T02:13:36.403066+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_cab.py', '--cfg-path', '/tmp/tmp735ptf0l']
[2024-04-29T02:14:18.504+0000] {standard_task_runner.py:91} INFO - Job 74: Subtask file_exception
[2024-04-29T02:14:18.550+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_yellow_cab.file_exception manual__2024-04-29T02:13:36.403066+00:00 [running]> on host b97262715cd8
[2024-04-29T02:14:18.637+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_yellow_cab' AIRFLOW_CTX_TASK_ID='file_exception' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T02:13:36.403066+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T02:13:36.403066+00:00'
[2024-04-29T02:14:18.639+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T02:14:18.653+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-29T02:14:18.654+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T02:14:18.663+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_yellow_cab, task_id=file_exception, execution_date=20240429T021336, start_date=20240429T021418, end_date=20240429T021418
[2024-04-29T02:14:18.684+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T02:14:18.702+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T02:14:18.704+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
