[2024-04-30T05:02:01.289+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T05:02:01.320+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yellow_cab.load_data manual__2024-04-30T05:01:52.364584+00:00 [queued]>
[2024-04-30T05:02:01.331+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yellow_cab.load_data manual__2024-04-30T05:01:52.364584+00:00 [queued]>
[2024-04-30T05:02:01.331+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T05:02:01.344+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2024-04-30 05:01:52.364584+00:00
[2024-04-30T05:02:01.352+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-30T05:02:01.356+0000] {standard_task_runner.py:63} INFO - Started process 84 to run task
[2024-04-30T05:02:01.361+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_yellow_cab', 'load_data', 'manual__2024-04-30T05:01:52.364584+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpr5mas1ql']
[2024-04-30T05:02:01.368+0000] {standard_task_runner.py:91} INFO - Job 169: Subtask load_data
[2024-04-30T05:02:01.458+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_yellow_cab.load_data manual__2024-04-30T05:01:52.364584+00:00 [running]> on host 9b76f5e7e2c9
[2024-04-30T05:02:01.588+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_yellow_cab' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T05:01:52.364584+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T05:01:52.364584+00:00'
[2024-04-30T05:02:01.591+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T05:02:01.733+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T05:02:01.734+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/scripts.py", line 38, in load_files
    file_upload(filename,engine)
  File "/opt/airflow/dags/scripts/scripts.py", line 43, in file_upload
    df = pd.read_parquet(filepath)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 272, in read
    pa_table = self.api.parquet.read_table(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/parquet/core.py", line 1776, in read_table
    dataset = ParquetDataset(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/parquet/core.py", line 1343, in __init__
    [fragment], schema=schema or fragment.physical_schema,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_dataset.pyx", line 1367, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '<Buffer>': Parquet file size is 0 bytes
[2024-04-30T05:02:01.745+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dag_yellow_cab, task_id=load_data, execution_date=20240430T050152, start_date=20240430T050201, end_date=20240430T050201
[2024-04-30T05:02:01.758+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 169 for task load_data (Could not open Parquet input source '<Buffer>': Parquet file size is 0 bytes; 84)
[2024-04-30T05:02:01.784+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-30T05:02:01.808+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T05:02:01.812+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
