[2024-04-29T19:16:40.654+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T19:16:40.673+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yellow_cab.copy_into_table manual__2024-04-29T19:15:59.135384+00:00 [queued]>
[2024-04-29T19:16:40.680+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yellow_cab.copy_into_table manual__2024-04-29T19:15:59.135384+00:00 [queued]>
[2024-04-29T19:16:40.681+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T19:16:40.693+0000] {taskinstance.py:2327} INFO - Executing <Task(CopyFromExternalStageToSnowflakeOperator): copy_into_table> on 2024-04-29 19:15:59.135384+00:00
[2024-04-29T19:16:40.698+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T19:16:40.700+0000] {standard_task_runner.py:63} INFO - Started process 87 to run task
[2024-04-29T19:16:40.700+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_yellow_cab', 'copy_into_table', 'manual__2024-04-29T19:15:59.135384+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_cab.py', '--cfg-path', '/tmp/tmps44nnbk1']
[2024-04-29T19:16:40.703+0000] {standard_task_runner.py:91} INFO - Job 116: Subtask copy_into_table
[2024-04-29T19:16:40.743+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_yellow_cab.copy_into_table manual__2024-04-29T19:15:59.135384+00:00 [running]> on host 18e1bee5b33c
[2024-04-29T19:16:40.826+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_yellow_cab' AIRFLOW_CTX_TASK_ID='copy_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T19:15:59.135384+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T19:15:59.135384+00:00'
[2024-04-29T19:16:40.827+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T19:16:40.840+0000] {copy_into_snowflake.py:143} INFO - Executing COPY command...
[2024-04-29T19:16:40.850+0000] {base.py:84} INFO - Using connection ID 'yellowcab_proyect' for task execution.
[2024-04-29T19:16:40.851+0000] {connection.py:386} INFO - Snowflake Connector for Python Version: 3.7.1, Python Version: 3.12.2, Platform: Linux-6.6.22-linuxkit-x86_64-with-glibc2.36
[2024-04-29T19:16:40.852+0000] {connection.py:1211} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-04-29T19:16:41.166+0000] {cursor.py:1032} INFO - query: [ALTER SESSION SET autocommit=True]
[2024-04-29T19:16:41.238+0000] {cursor.py:1045} INFO - query execution done
[2024-04-29T19:16:41.239+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-04-29T19:16:41.240+0000] {sql.py:457} INFO - Running statement: COPY INTO PUBLIC.YELLOWCAB_DATA
             FROM  @%YELLOWCAB_DATA/
        
        
        FILE_FORMAT=(type = 'parquet', MATCH_BY_COLUMN_NAME = 'CASE_SENSITIVE'), parameters: None
[2024-04-29T19:16:41.240+0000] {cursor.py:1032} INFO - query: [COPY INTO PUBLIC.YELLOWCAB_DATA FROM  @%YELLOWCAB_DATA/   FILE_FORMAT=(type = 'p...]
[2024-04-29T19:16:41.310+0000] {cursor.py:1045} INFO - query execution done
[2024-04-29T19:16:41.316+0000] {connection.py:734} INFO - closed
[2024-04-29T19:16:41.363+0000] {connection.py:740} INFO - No async queries seem to be running, deleting session
[2024-04-29T19:16:41.413+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T19:16:41.414+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/transfers/copy_into_snowflake.py", line 144, in execute
    self._result = self.hook.run(  # type: ignore # mypy does not work well with return_dictionaries=True
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 390, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1136, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001006 (22023): 01b3ffc4-0000-542b-0000-0000d81d40fd: SQL compilation error:
invalid parameter 'MATCH_BY_COLUMN_NAME'
[2024-04-29T19:16:41.424+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dag_yellow_cab, task_id=copy_into_table, execution_date=20240429T191559, start_date=20240429T191640, end_date=20240429T191641
[2024-04-29T19:16:41.437+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 116 for task copy_into_table (001006 (22023): 01b3ffc4-0000-542b-0000-0000d81d40fd: SQL compilation error:
invalid parameter 'MATCH_BY_COLUMN_NAME'; 87)
[2024-04-29T19:16:41.456+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T19:16:41.471+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T19:16:41.473+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
